const EXPERIENCES = [
  {
    id: 1,
    name: "Cà phê check‑in nhanh",
    category: "Nghỉ ngơi",
    type: "Micro",
    minTime: 15,
    maxTime: 45,
    avgDuration: 30,
    distanceKm: 0.3,
    openFrom: 7,
    openTo: 23,
    priceRange: "30k–60k",
    rating: 4.2,
    bookingAvailable: false,
    partner: "Cafe Corner"
  },
  {
    id: 2,
    name: "Ăn nhanh món địa phương",
    category: "Ẩm thực",
    type: "Short",
    minTime: 30,
    maxTime: 60,
    avgDuration: 45,
    distanceKm: 0.8,
    openFrom: 10,
    openTo: 22,
    priceRange: "50k–120k",
    rating: 4.6,
    bookingAvailable: true,
    partner: "Bún Phố Cổ"
  },
  {
    id: 3,
    name: "Spa mini thư giãn",
    category: "Nghỉ ngơi",
    type: "Short",
    minTime: 60,
    maxTime: 120,
    avgDuration: 90,
    distanceKm: 1.2,
    openFrom: 9,
    openTo: 21,
    priceRange: "150k–300k",
    rating: 4.4,
    bookingAvailable: true,
    partner: "Mini Spa Relax"
  },
  {
    id: 4,
    name: "Tham quan phố cổ",
    category: "Khám phá",
    type: "Medium",
    minTime: 120,
    maxTime: 240,
    avgDuration: 180,
    distanceKm: 0.5,
    openFrom: 0,
    openTo: 24,
    priceRange: "Miễn phí",
    rating: 4.8,
    bookingAvailable: false,
    partner: "Tour đi bộ"
  }
];
